version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: hbnb_dev
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - ENV=${ENV}
      - PORT=${PORT}
      - REPOSITORY=${REPOSITORY}
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  db_data:
