"""Schema update

Revision ID: 221b797c0e87
Revises: b83cfdee6022
Create Date: 2024-07-03 13:03:12.224016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '221b797c0e87'
down_revision: Union[str, None] = 'b83cfdee6022'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('countries', 'id')
    op.alter_column('countries', 'code', existing_type=sa.String(length=2), nullable=False, primary_key=True)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('id', sa.String(length=36), nullable=False))
    op.alter_column('countries', 'code', existing_type=sa.String(length=2), nullable=True, primary_key=False)
    # ### end Alembic commands ###
